language: python
python:
- '3.7'
sudo: required
install:
- pip install flask
script:
- python test.py
deploy:
  provider: heroku
  app: devops4labcelso
  api_key:
    secure: Ud1gIcb0xOjs/eouwf0ao6e4E4AylLo56eIr2032ore55MvYpAbuv5HIvfNEmNJW2NAivEFWZLqxxD773SuoYCaVqZD85xQMxQE7bzLnEOSm29xVo/e2uvlpf39VR8K7Xy72kKuLH3ZfFcp2JTHCd7XMT8D1RZuVg16i13OGXJAnZoXtAqEtrQhJrLeTtoLY94H3XVpJYeJvZYAtZft7VrxTlYvCn6b4z640saPIpglWDJRxBHZ4JKA2prQaMMqLXuI9Qwn9MExzaW1JMMy/7PHrd5i9AZ4sxWfprJR13J36Koww0ABu+Vceca+NddffA5DVWAkf8FyzYB77QkrB6IOsExR+XgnWbWQuXd6wLRpFCukILHeQNjb7n+0uHaouM7sCxMDU5J35BPpLTjva2YOFHZvAY3EVcYfC5z+2aiSkWE6xKiJlBYqaxWTxw/EIRYTrOsffiHTAE4dt1oyhxAL0G9xDORlJk9/OpvJQjeg2Nc6FOCnD6bNsYt9+sUhfkC+BOrQZ128iOvhE6U7akkh6ZurDEUtwa0cVl68pQZzGUMiqQvPiH6fhyNDxxA6Plt0V29RL81l+aSaVyJMv3FXAP0to8KiY3aWBGppGcj2Az8a3lNHUpy/Jp3rmA+J46h1JxQSC/u5mQtVdumXkEKzKZr0PLLnvGZ5l1leosII=
